### PR TITLE
Update plugin name & main description to include Openverse alongside the other services.

### PR DESCRIPTION
**Pull request by KZeni**
There were just a few other spots where the other services were being listed that Openverse needed to be added to as well.

### CODE REVIEW

**Review by dcooney — APPROVED** [review]

**Comment by dcooney** [comment]
Thanks so much! Totally missed all this stuff :)

**Comment by KZeni** [comment]
No worries! I'm glad to have an all-in-one plugin for this sort of thing so thanks for all your work on this!

**Comment by AetherUnbound** [comment]
This is so cool to see! 😄 Thank you both for this!

**Comment by KZeni** [comment]
I think the thanks should really all go to @dcooney for their work. My contribution here was tiny compared to everything they did to make this happen.

**Pull request merged**
