### PR TITLE
Return value instead of echoing it in `admin_footer_text` callback

### PR DESCRIPTION
**Pull request by TobiasBg**
Filter hook callbacks must `return` their value, and not directly `echo` it.

This otherwise creates problem for other plugins (like mine), as they then get passed `null` as the filter hook variable.

### CODE REVIEW

**Comment by dcooney** [comment]
@TobiasBg In testing this PR it returns nothing for me. Did it work for you?
image

**Comment by TobiasBg** [comment]
Hi @dcooney,

yes, this is working for me. Here's a screenshot of the bottom of the settings screen:
instant-images

The existing code will produce the exact same HTML output, but it's the wrong use of a plugin filter hook. These must always only modify and return the filter variable (`$text` in this case), and not directly `echo` any output.

**Comment by dcooney** [comment]
Interesting, it actually does work but not when ACF Pro is also activated 🤔

**Comment by TobiasBg** [comment]
That could actually mean that ACF Pro contain a very similar bug. I don't have access to its code, can you maybe search for its `admin_footer_text` filter hook callback and check that?

**Comment by dcooney** [comment]
🤦‍♂️ I lied, the issue is my [Block Manager](https://wordpress.org/plugins/block-manager/) plugin as I echo the value the same way.
https://wordpress.org/plugins/block-manager/

**Comment by dcooney** [comment]
Thanks @TobiasBg  🥳

**Comment by TobiasBg** [comment]
Hi @dcooney,

great! Good to hear that this helped!
Indeed, Block Manager does the same, so the same change should be applied there as well! Would you like me to create a PR?

Best wishes,
Tobias

**Comment by dcooney** [comment]
All good. I've made the change to `main` on that plugin as well. just haven't done a release yet.

**Pull request merged**
